/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_contexts_IMU */

#ifndef _Included_com_contexts_IMU
#define _Included_com_contexts_IMU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_contexts_IMU
 * Method:    updateContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_contexts_IMU_updateContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
